INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ioanDanin@gmail.com', 'ioan123321');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('Donald2003@gmail.com', 'qawsedrf123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ArsenKrasen@gmail.com', '1234321qwe');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('KolinKrivi@gmail.com', 'CallMeKolin1');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('untouchable@gmail.com', 'untouchable123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('impossible@gmail.com', 'whyNot123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('Obarang@gmail.com', 'bamRang321');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('StyleDis@gmail.com', 'simpleS1mple');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('kibertroon2002@gmail.com', 'people123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('visunello1@gmail.com', 'AlwaysSad1');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('globusSuper@DireElective.com', 'globus123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('IrinaLukos@DireElective.com', 'irina123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('AdamLebedev@DireElective.com', 'adam123123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('EvaGoncharova@DireElective.com', 'eva123123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('SergeySmirnov@DireElective.com', 'sergey123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('OlgaBaranova@DireElective.com', 'olga123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('SofiaBlinova@DireElective.com', 'sofia123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('AnastasiaLotova@DireElective.com', 'anastasia123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('AlekBezrodny@DireElective.com', 'alek123123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('AlexGolubev@DireElective.com', 'alex123123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('AndreyZhigunov@DireElective.com', 'andrey123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('DinaraOnegina@DireElective.com', 'dinara123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('LevBorovskih@DireElective.com', 'lev123123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('AnastasiaKipel@DireElective.com', 'anastasia123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('KonstantinKriv@DireElective.com', 'konstantin123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('MaksymSahno@DireElective.com', 'maksym123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('DominikaNota@DireElective.com', 'dominika123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('KiraZlatova@DireElective.com', 'kira123123');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('gawarrannuf-6223@gmail.com', 'gawarrannuf6223');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('goddubivyk-5217@gmail.com', 'goddubivyk5217');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('apogeppex-1285@gmail.com', 'apogeppex1285');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('amezuppyqo-3080@gmail.com', 'amezuppyqo3080');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('eqossadi-8105@gmail.com', 'eqossadi8105');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('loppollaqorr-0076@gmail.com', 'loppollaqorr0076');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('bugeqexeg-5289@gmail.comн', 'bugeqexeg5289');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('emmylaffu-6905@gmail.com', '6905');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('jenassassy-7589@gmail.com', 'jenassassy7589');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('mejobettuv-3015@gmail.com', 'mejobettuv3015');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ossiraga-8969@gmail.com', 'ossiraga8969');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ruruvepudd-1888@gmail.com', 'ruruvepudd1888');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('gynunnocesa-5989@gmail.com', 'gynunnocesa5989');

INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('enattocob-3132@gmail.com', 'enattocob3132');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ommixittumm-7495@gmail.com', 'ommixittumm7495');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('urinakevu-2957@gmail.com', 'urinakevu2957');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('uvittinogi-6833@gmail.com', 'uvittinogi6833');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('erreleppeqo-3680@gmail.com', 'erreleppeqo3680');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ossydafudd-6072@gmail.com', 'ossydafudd6072');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('hokeppesyvi-1493@gmail.com', 'hokeppesyvi1493');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ujarreko-7270@gmail.com', 'ujarreko7270');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('bewessihut-3552@gmail.com', 'bewessihut3552');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('pittotabi-7402@gmail.com', 'pittotabi7402');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ulleppazo-3811@gmail.com', 'ulleppazo3811');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('sossarecac-3348@gmail.com', 'sossarecac3348');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('cilevavy-9064@gmail.com', 'cilevavy9064');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ewulleqy-8772@gmail.com', 'ewulleqy8772');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('jadovuppew-3234@gmail.com', 'jadovuppew3234');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('nevemmuhak-1821@gmail.com', 'nevemmuhak1821');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('jerrekamme-4257@gmail.com', 'jerrekamme4257');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('uvamedax-2962@gmail.com', 'uvamedax2962');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('toxidaddyji-7183@gmail.com', 'toxidaddyji7183');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('pammaxoddezo-5149@gmail.com', 'pammaxoddezo5149');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('fynnexusudda-1466@gmail.com', 'fynnexusudda1466');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ikyjona-8192@gmail.com', 'ikyjona8192');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('towesejus-6603@gmail.com', 'towesejus6603');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('keleddopos-2696@gmail.com', 'keleddopos2696');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('essuffeqofe-0066@gmail.com', 'essuffeqofe0066');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('coravyppa-7891@gmail.com', 'coravyppa7891');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('vakareneff-4989@gmail.com', 'vakareneff4989');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('sawebeffa-9836@gmail.com', 'sawebeffa9836');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('pizamifutte-5311@gmail.com', 'pizamifutte5311');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('avokuddu-0800@gmail.com', 'avokuddu0800');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ottymmikud-1921@gmail.com', 'ottymmikud1921');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ommupuseq-4158@gmail.com', 'ommupuseq4158');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('orrikefa-9374@gmail.com', 'orrikefa9374');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('syssadenett-0274@gmail.com', 'syssadenett0274');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('arimawe-0086@gmail.com', 'arimawe0086');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('ofeteka-6127@gmail.com', 'ofeteka6127');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('vilavippappy-6563@gmail.com', 'vilavippappy6563');
INSERT INTO USER (USER_EMAIL, USER_PASSWORD) VALUES ('lacynnocep-2750@gmail.com', 'lacynnocep2750');

INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Nikolay', 'Globus', '1972-10-20', 1);
INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Irina', 'Lukos', '1969-08-11', 2);
INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Adam', 'Lebedev', '1971-11-16', 3);
INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Eva', 'Goncharova', '1976-04-01', 4);
INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Sergey', 'Smirnov', '1979-12-10', 5);
INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Olga', 'Baranova', '1961-02-15', 6);
INSERT INTO TEACHER (TEACHER_NAME, TEACHER_SURNAME,TEACHER_BIRTH_DATE, USER_ID) VALUES ('Sofia', 'Blinova', '1965-03-28', 7);

INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Ivan', 'Jigun', 0, '1998-06-06', 8);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Donald', 'Vlasenko', 0, '2001-04-17', 9);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Arsen', 'Krasnov', 0, '2000-01-02', 10);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Kolin', 'Krivi', 0, '1999-12-13', 11);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Nikita', 'Chyjikov', 0, '1996-10-14', 12);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Roman', 'Kolomiets', 0, '1991-10-04', 13);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Daniil', 'Khusnulin', 0, '1997-10-22', 14);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Kyril', 'Loboda', 0, '2001-08-28', 15);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Svetlana', 'Bescherevnih', 0, '2002-01-13', 16);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Victoria', 'Shevchuk', 0, '2000-07-21', 17);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Denys', 'Karavaev', 0, '2000-08-15', 18);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Artem', 'London', 0, '2000-08-06', 19);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Novad', 'Demchinko', 0, '2002-01-08', 20);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Natalia', 'Dalik', 0, '1959-05-13', 21);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Georgi', 'Lapitin', 0, 0, '1998-10-09', 22);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Amy', 'Rozymkova', 0, 0, '1991-11-21', 23);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Betty', 'Kloden', 0, '1997-06-17', 24);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Ivan', 'Legon', 0, '2002-04-01', 25);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Robert', 'Kacharan', 0, '1997-03-21', 26);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Camille', 'Nolatova', 0, '1966-06-06', 27);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Charlotte', 'Lavandova', 0, '1986-04-26', 28);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Elizabeth', 'Olazova', 0, '1989-01-22', 29);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Yevhen', 'Selezen', 0, '1966-10-21', 30);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Pylyp', 'Krasnii', 0, '1999-01-15', 31);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Viktor', 'Zohan', 0, '1997-08-14', 32);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Serhiy', 'Drujba', 0, '1993-04-04', 33);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Jane', 'Mizgina', 0, '1997-10-22', 34);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Irene', 'Jlodavna', 0, '2000-09-15', 35);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Shon', 'Follavat', 0, '2001-06-18', 36);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Rose', 'Kalli', 0, '1998-11-27', 37);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Ruslan', 'Kovalenko', 0, '1995-05-11', 38);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Alex', 'Skiba', 0, '1997-05-18', 39);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Taras', 'Pozdnii', 0, '1997-08-22', 40);
INSERT INTO STUDENT (STUDENT_NAME, STUDENT_SURNAME, STUDENT_BAN_STATUS, STUDENT_BIRTH_DATE, USER_ID)
VALUES ('Denys', 'Kutsenko', 0, '1991-02-15', 41);

INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Mykyta', 'Cherevko', '1994-11-22', 42);
INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Oleksandr', 'Kyrilenko','2003-01-04', 43);
INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Victoria', 'Chernyak', '2001-06-11', 44);
INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Diana', 'Vladimirova', '1996-08-15', 45);
INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Dmitri', 'Frolov', '2000-08-18', 46);
INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Ludmila', 'Dalovna', '1998-06-13', 47);
INSERT INTO administrator (ADMINISTRATOR_NAME, ADMINISTRATOR_SURNAME, ADMINISTRATOR_BIRTH_DATE, USER_ID)
VALUES ('Maksym', 'Gnezdov', '1995-07-07', 48);

INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning useful PHP tricks', 'PHP useful tricks', '2019-05-04', '2019-05-14', 1);
INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning advanced Java', 'Java advanced course', '2018-06-01', '2019-01-02', 2);
INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning the basics of PHP', 'PHP basic course', '2020-11-12', '2021-01-01', 3);

INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning useful Ruby tricks', 'Ruby tricks course', '2021-02-27', '2021-03-11', 4);

INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning advanced C#', 'C# advanced course', '2020-11-10', '2021-03-17', 5);

INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning useful Python tricks', 'Python tricks course', '2021-04-10', '2021-07-11', 6);
INSERT INTO COURSE (COURSE_THEME, COURSE_NAME, COURSE_START_DATE, COURSE_END_DATE, TEACHER_ID) VALUES ('Learning advanced PHP', 'PHP advanced course', '2021-05-18', '2022-01-01', 7);

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (8,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (8,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (8,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (8,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (9,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (9,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (9,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (9,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (10,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (10,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (10,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (10,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (11,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (11,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (11,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (11,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (12,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (12,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (12,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (12,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (12,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (13,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (13,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (13,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (13,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (14,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (14,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (14,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (14,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (15, 1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (15, 2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (15, 3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (15, 4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (16,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (16,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (16,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (16,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (17,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (17,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (17,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (17,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (18,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (18,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (18,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (18,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (19,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (19,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (19,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (19,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (20,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (20,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (20,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (20,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (20,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (21,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (21,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (21,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (21,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (22,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (22,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (22,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (22,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (23, 1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (23, 2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (23, 3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (23, 4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (24, 1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (24,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (24,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (24,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (25,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (25,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (25,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (26,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (26,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (26,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (26,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (26,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (27,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (27,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (27,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (27,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (28,7);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (28,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (28,5);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (28,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (28,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (29,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (29,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (29,3);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (29,6);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (29,4);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (30,1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (30,2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (30,5);
